version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: metrito-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: metrito-redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
