import path from 'node:path';

import moment from 'moment';
import { format, transports } from 'winston';
import DailyRotateFile from 'winston-daily-rotate-file';

import utils from '@shared/utils';

import loggerConfig from '../config';

/**
 * Format for logging HTTP-related information to files.
 */
const fileHttpFormat = format.combine(
  /**
   * Display the timestamp (date and time) when the log was added.
   */
  format.timestamp(),

  /**
   * Inject the path where the log was triggered.
   * Correct the UTC of the timestamp.
   */
  format((info) => {
    const path = utils.currentPath();
    info.path = path || null;

    if (info.timestamp) {
      info.timestamp = moment(info.timestamp).utc(true).format();
    }

    return info;
  })(),

  /**
   * Inject metadata fields generated by requests and responses.
   */
  format.metadata({
    fillExcept: ['message', 'level', 'timestamp', 'path'],
  }),

  /**
   * Format the log as JSON.
   */
  format.json(),

  /**
   * Make the JSON readable.
   */
  format.prettyPrint(),
);

type Transport = transports.FileTransportInstance | DailyRotateFile;

const fileHttpTransports: Transport[] = [];

if (loggerConfig.STORE_HTTP_ERROR_LOGS) {
  fileHttpTransports.push(
    new DailyRotateFile({
      filename: path.resolve(
        loggerConfig.HTTP_ERROR_LOGS_DIR,
        'http_errors-%DATE%',
      ),
      extension: loggerConfig.LOGS_FILE_EXTENSION,
      format: fileHttpFormat,
      maxSize: loggerConfig.MAX_SIZE_PER_FILE,
      zippedArchive: loggerConfig.LOGS_FILE_ZIPPED,
      level: loggerConfig.INCLUDES_400_ERRORS ? 'warn' : 'error',
    }),
  );
}

export { fileHttpTransports };
